// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTdSv-hw9MDQT56OhtOed7_O9NuEntVc',
    appId: '1:903340585593:web:587b9c0119e298f3c15aa8',
    messagingSenderId: '903340585593',
    projectId: 'multi-lang-chat-aec00',
    authDomain: 'multi-lang-chat-aec00.firebaseapp.com',
    storageBucket: 'multi-lang-chat-aec00.appspot.com',
    measurementId: 'G-MZK4W5YMR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkQDcayRMFA7SIZwKHXuo2d_zD6mHm8c',
    appId: '1:903340585593:android:52634aca07eb8422c15aa8',
    messagingSenderId: '903340585593',
    projectId: 'multi-lang-chat-aec00',
    storageBucket: 'multi-lang-chat-aec00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49oWAvL6SwdzFlgSkfOv6VAhfUbJgBIM',
    appId: '1:903340585593:ios:d370dcf5edec0e63c15aa8',
    messagingSenderId: '903340585593',
    projectId: 'multi-lang-chat-aec00',
    storageBucket: 'multi-lang-chat-aec00.appspot.com',
    iosClientId: '903340585593-k16jgh5sj4ipn9uuhgsh9ukflmt7khcb.apps.googleusercontent.com',
    iosBundleId: 'pl.drelich.multiLangChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC49oWAvL6SwdzFlgSkfOv6VAhfUbJgBIM',
    appId: '1:903340585593:ios:d370dcf5edec0e63c15aa8',
    messagingSenderId: '903340585593',
    projectId: 'multi-lang-chat-aec00',
    storageBucket: 'multi-lang-chat-aec00.appspot.com',
    iosClientId: '903340585593-k16jgh5sj4ipn9uuhgsh9ukflmt7khcb.apps.googleusercontent.com',
    iosBundleId: 'pl.drelich.multiLangChat',
  );
}
